# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 앤드류의 개발 블로그 | 성장 합시다.
email: umanking@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Software Engineer
  # 주로 Java, Spring, JPA를 다루며 클린코드, 클린 아키텍쳐, 디자인패턴 활용하는 것을 지향합니다.
  # 소프트웨어 엔지니어는 문제를 해결하는 사람이라고 생각합니다.
  # 개발방법론, 효율적인 프로세스, 업무환경에 대한 관심이 많습니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://umanking.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: umanking87
github_username:  umanking

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-last-modified-at
whitelist:
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default.
# Anfy item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

google_fonts: "Nanum+Gothic:400,700"
highlighter: rouge
permalink: /:categories/:title/
